backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projets"
    label_singular: "Projet"
    delete: false
    editor:
      preview: false
    files:
      - file: "data/projects.json"
        label: "Liste des projets"
        name: "projects"
        format: "json"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Catégorie", name: "category", widget: "string" }
          - { label: "Image principale", name: "image", widget: "image" }
          - label: "Galerie"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
          - { label: "Lien démo", name: "demo", widget: "string", required: false }
          - { label: "Lien code", name: "code", widget: "string", required: false }
          - { label: "Fonctionnalités", name: "features", widget: "list" }
          - { label: "Tags", name: "tags", widget: "list" }
          - label: "Détails"
            name: "details"
            widget: "object"
            fields:
              - { label: "Objectif", name: "objectif", widget: "text" }
              - { label: "Stack", name: "stack", widget: "string" }
              - { label: "Challenges", name: "challenges", widget: "text" }